apiVersion: v2
name: karpenter-core-crd
description: Core APIs CRDs, and everything else that is part of karpenter-core
type: application
version: 0.0.2
appVersion: 0.0.2
keywords:
  - cluster
  - node
  - scheduler
  - autoscaling
  - lifecycle
home: https://karpenter.sh/
icon: https://repository-images.githubusercontent.com/278480393/dab059c8-caa1-4b55-aaa7-3d30e47a5616
sources:
  - https://github.com/aws/karpenter-core/
