apiVersion: {{ include "karpenter-core.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.podDisruptionBudget.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
    {{- include "karpenter-core.selectorLabels" . | nindent 6 }}
