name: InstallPrometheus
description: 'Installs prometheus'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: install
      shell: bash
      run: |
        hack/install-prometheus.sh
