name: InstallPrometheus
description: 'Installs prometheus'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: install
      shell: bash
      run: |
        hack/install-prometheus.sh
