name: InstallPrometheus
description: 'Installs prometheus'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - name: install
      shell: bash
      run: |
        hack/install-prometheus.sh
