name: InstallPrometheus
description: 'Installs prometheus'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: install
      shell: bash
      run: |
        hack/install-prometheus.sh
