---
name: Bug Report
about: Report a bug
title: ''
labels: bug
assignees: ''

---

**Observed Behavior**:

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 
- Kubernetes Version (`kubectl version`): 