name: presubmit
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  presubmit:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8sVersion: ["1.25.0", "1.26.x", "1.27.x", "1.28.x", "1.29.x", "1.30.x"]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: ./.github/actions/install-deps
      with:
        k8sVersion: ${{ matrix.k8sVersion }}
    - name: Enable the actionlint matcher
      run: echo "::add-matcher::.github/actionlint-matcher.json"
    - run: K8S_VERSION=${{ matrix.k8sVersion }} make presubmit
    - name: Send coverage
      # should only send converage once https://docs.coveralls.io/parallel-builds
      if: matrix.k8sVersion == '1.30.x'
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
