name: presubmit
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  presubmit:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          k8sVersion: ["1.23.x", "1.24.x", "1.25.x", "1.26.x", "1.27.x", "1.28.x"]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-deps
      with:
        k8sVersion: ${{ matrix.k8sVersion }}
    - name: Enable the actionlint matcher
      run: echo "::add-matcher::.github/actionlint-matcher.json"
    - run: K8S_VERSION=${{ matrix.k8sVersion }} make presubmit
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github
